config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts
  resources :users, only: %i[show index]
  resources :comments, only: %i[create destroy update edit]
  resources :likes, only: %i[create destroy]
  resources :friendships, only: %i[create update destroy]

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :add_profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendship_sent, class_name: 'Friendship',
                             foreign_key: 'user1_id', dependent: :destroy
  has_many :friendship_received, class_name: 'Friendship',
                                 foreign_key: 'user2_id', dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def find_friendships(friend_id)
    Friendship.find_by_sql(['SELECT * FROM friendships WHERE  ((user1_id= ? and user2_id = ?)
    OR (user1_id= ? and user2_id = ?)) AND status = true ', id, friend_id, friend_id, id])
  end

  def find_friendships_pending(friend_id)
    Friendship.find_by_sql(['SELECT * FROM friendships WHERE  ((user1_id= ? AND user2_id = ?)
    OR (user1_id= ? and user2_id = ?)) AND status = false ', id, friend_id, friend_id, id])
  end

  def find_friends
    User.find_by_sql(['SELECT * FROM users WHERE id IN
    (
      SELECT CASE WHEN user1_id=? THEN user2_id ELSE user1_id END
      FROM friendships WHERE (user1_id= ? OR user2_id = ?) AND status = true
      )', id, id, id])
  end

  def pending_friends
    User.find_by_sql(['SELECT * FROM users WHERE id IN
    (
      SELECT CASE WHEN user1_id=? THEN user2_id ELSE user1_id END
      FROM friendships
       WHERE (user1_id= ? OR user2_id = ?) AND status = false
    )', id, id, id])
  end

  private

  def add_profile_image
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    self.image_link = gravatar_url
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @post = Post.new
  end

  def index
    filter = params[:filter]
    if filter == 'friends'
      @users = current_user.find_friends
    elsif filter == 'pending'
      @users = current_user.friendship_received.map { |u| u.sender if u.receiver == current_user && u.status == false }
      @users.compact!
    else
      @users = User.all
    end
  end
end

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <% @users.each do |u|%>
    <div class="col-md-3 px-1 mb-2 text-center ">
      <div class='w-100 h-100 shadow-sm py-4 px-3 bg-white rounded'>
        <%= image_tag u.image_link, class:'rounded-circle', alt:'Profile picture' %>
        <%= link_to u.name, user_path(u), class: 'h5 mt-2 mb-0 d-block'%>
        <small class='text-muted pt-0'><%=u.email%></small>
        <small class='text-muted d-block pt-0'>Joined <%= time_ago_in_words u.created_at %> ago</small>
        <%if current_user != u%>
        <% if u.find_friends.any?{ |f| f==current_user} %>
        <%= link_to friendship_path(id:u.id),class:'btn text-white btn-block btn-sm bg-danger mt-3', method: :delete do %>
        <i class="fa fa-minus-circle"></i> Remove friend
        <% end %>
        <% elsif u.pending_friends.any?{ |f| f==current_user} %>
        <%= accept_reject_pending(u.id) %>
        <% else %>
        <%= link_to friendships_path(user_id:u.id), class: "btn text-white btn-block btn-sm bg-teal mt-3", method: :post do%>
        <span class=" fa fa-user-plus"></span> Add as friend
        <% end %>

        <%end%>
        <%end%>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-4 ">
    <div class='shadow-sm rounded px-2 py-5 mb-2 text-center bg-teal'>
      <%= image_tag @user.image_link+'?s=200', class:'img-fluid rounded-circle', alt:'Profile picture' %>
      <div class='h5 mt-2 mb-0'><%=@user.name%></div>
      <small class='text-muted pt-0'><%=@user.email%></small>
      <small class='text-muted d-block pt-0'>Joined <%= time_ago_in_words @user.created_at %> ago</small>
      <%if current_user != @user%>
      <% if @user.find_friends.any?{ |f| f==current_user} %>
      <%= link_to friendship_path(id:@user.id),class:'btn text-white btn-block btn-sm bg-danger mt-3', method: :delete do %>
      <i class="fa fa-minus-circle"></i> Remove friend
      <% end %>
      <% elsif @user.pending_friends.any?{ |f| f==current_user} %>
      <%= accept_reject_pending(@user.id) %>
      <% else %>
      <%= link_to friendships_path(user_id:@user.id), class: "btn text-white btn-block btn-sm bg-teal mt-3", method: :post do%>
      <span class=" fa fa-user-plus"></span> Add as friend
      <% end %>

      <%end%>
      <%end%>
</div>
    </div>
    
    <div class="col-lg-8 mx-auto">

   
    <% if @user == current_user || @user.find_friends.any?{ |f| f==current_user}%>
    <div class="mx-auto">
      <%= render "posts/form", text:'Update post'%>
    </div>
    <% @user.posts.each do |p| %>
    <div class="card mb-3">
      <div class="card-header m-0 py-1 row bg-white">
        <div class="col-xs-2 mr-2">
          <%= image_tag p.author.image_link+"?s=50", class:"rounded-circle img-fluid" %>
        </div>
        <div class="col-xs-10 text-left">
          <%= link_to p.author.name, user_path(p.author), class: ''%>
          <br />
          Published : <%= time_ago_in_words p.created_at %> ago
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= p.content %></p>
      </div>
      <div class="card-footer bg-teal py-1 d-flex align-items-center justify-content-between">
      <div>
        <% if p.likes.any? {|like| like.user == current_user}%>
        <%= link_to "",  like_path(id: p.id), 
            method: :delete,class:"fa fa-lg fa-thumbs-up text-dark" %>
        <% else %>
        <%= link_to "", likes_path(id: p.id),
            method: :post,class:"fa fa-lg fa-thumbs-up text-light" %>
        <% end %>
          <div class="d-inline ">
            <% if p.likes.count != 0%>
              <%= p.likes.count %>
              
            <% end %> 
          </div>
        </div>
        <div class="float-right">
          <%= link_to "Comments", post_path(p),class:"btn btn-sm btn-light" %>
          <% if current_user == p.author %>
          <%= link_to "Edit", edit_post_path(p), class:"btn btn-sm btn-light" %>
          <%= link_to "Delete", post_path(p), method: :delete, class:"btn btn-sm btn-danger" %>
          <%end%>
        </div>
      </div>
    </div>
    <% end %>

      <% else %>
      <div class='shadow-sm rounded px-2 py-5 mb-2 text-center bg-white'>You can't see this users posts, you need to add
        Them as friend!</div>
      <% end %>


    </div>
  </div>
</div>