config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts
  resources :users, only: %i[show index]
  resources :comments, only: %i[create destroy update edit]
  resources :likes, only: %i[create destroy]
  resources :friendships, only: %i[create update destroy]

end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :content, length: { maximum: 255 }, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_post, only: %i[show edit destroy update]
  before_action only: %i[update edit destroy] do
    owner?(@post.author)
  end

  def index
    @post = Post.new
    @posts = current_user.posts
    current_user.find_friends.each { |user| @posts += user.posts }
    @posts = @posts.sort { |a, b| b.created_at - a.created_at } unless @posts.empty?
  end

  def new
    @post = Post.new
  end

  def create
    user = current_user
    @post = user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @new_comment = Comment.new
    @comments = @post.comments
    @comments = @comments.sort { |a, b| a.created_at - b.created_at } unless @comments.empty?
  end

  def edit; end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def check_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_comment_form.html.erb
<% if current_page?(post_path(@post))%>
<h5 class='text-center text-white mt-3' >Add new comment:</h5>
<% else %>
<h5 class='text-center text-white mt-3'>Edit this comment:</h5>
<% end %>

<%= form_for @new_comment, html: {class:"mb-4"} do |f| %>
<% if @new_comment.errors.any? %>
<% @new_comment.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<% end %>
<%= f.text_area :content,class:"textarea" %>
<%= f.hidden_field :post_id, value:@post.id%>
<%= f.submit "Submit",class:"btn btn-sm bg-teal btn-block mt-2" %>
<%end%>

app/views/posts/_form.html.erb
<%= form_for @post do |p|%>
<% if @post.errors.any? %>
  <ul class="list-group">
    <% @post.errors.full_messages.each do |message| %>
      <li class="list-group-item bg-warning"><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= p.text_area :content, class:"textarea text-center", placeholder:'Create new post!'%>
<%= p.submit value:"Create",class:"btn bg-teal btn-block mt-1 mb-3"%>
<% end %>

app/views/posts/edit.html.erb
<h2>Update post</h2>

<%= render "form"%>

app/views/posts/index.html.erb
<div class="mt-5">
  <div class="col-lg-8 mx-auto">
    <%= render "form", text:'Update post'%>
  </div>
  <div class="col-lg-8 mx-auto">
    <% @posts.each do |p| %>
    <div class="card mb-3">
      <div class="card-header m-0 py-1 row bg-white">
        <div class="col-xs-2 mr-2">
          <%= image_tag p.author.image_link+"?s=50", class:"rounded-circle img-fluid" %>
        </div>
        <div class="col-xs-10 text-left">
          <%= link_to p.author.name, user_path(p.author), class: ''%>
          <br />
          Published : <%= time_ago_in_words p.created_at %> ago
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= p.content %></p>
      </div>
      <div class="card-footer bg-teal py-1 d-flex align-items-center justify-content-between">
      <div>
        <% if p.likes.any? {|like| like.user == current_user}%>
        <%= link_to "",  like_path(id: p.id), 
            method: :delete,class:"fa fa-lg fa-thumbs-up text-dark" %>
        <% else %>
        <%= link_to "", likes_path(id: p.id),
            method: :post,class:"fa fa-lg fa-thumbs-up text-light" %>
        <% end %>
          <div class="d-inline ">
            <% if p.likes.count != 0%>
              <%= p.likes.count %>
              
            <% end %> 
          </div>
        </div>
        <div class="float-right">
          <%= link_to "Comments", post_path(p),class:"btn btn-sm btn-light" %>
          <% if current_user == p.author %>
          <%= link_to "Edit", edit_post_path(p), class:"btn btn-sm btn-light" %>
          <%= link_to "Delete", post_path(p), method: :delete, class:"btn btn-sm btn-danger" %>
          <%end%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
    <div class="card mb-3 mt-5">
      <div class="card-header m-0 py-1 row bg-white">
        <div class="col-xs-2 mr-2">
          <%= image_tag @post.author.image_link+"?s=50", class:"rounded-circle img-fluid" %>
        </div>
        <div class="col-xs-10 text-left">
          <%= link_to @post.author.name, user_path(@post.author), class: ''%>
          <br />
          Published : <%= time_ago_in_words @post.created_at %> ago
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= @post.content %></p>
      </div>
      <div class="card-footer bg-teal py-1 d-flex align-items-center justify-content-between">
      <div>
        <% if @post.likes.any? {|like| like.user == current_user}%>
        <%= link_to "",  like_path(id: @post.id), 
            method: :delete,class:"fa fa-lg fa-thumbs-up text-dark" %>
        <% else %>
        <%= link_to "", likes_path(id: @post.id),
            method: :post,class:"fa fa-lg fa-thumbs-up text-light" %>
        <% end %>
          <div class="d-inline ">
            <% if @post.likes.count != 0%>
              <%= @post.likes.count %>
              
            <% end %> 
          </div>
        </div>
        <div class="float-right">
          <% if current_user == @post.author %>
          <%= link_to "Edit", edit_post_path(@post), class:"btn btn-sm btn-light" %>
          <%= link_to "Delete", post_path(@post), method: :delete, class:"btn btn-sm btn-danger" %>
          <%end%>
        </div>
      </div>
    </div>
<% @comments.each do |comment|%>

    <div class="card mt-0">
      <div class="card-header m-0 row bg-teal">
        <div class="col-md-1">
          <%= image_tag comment.user.image_link+"?s=50", class:"rounded-circle" %>
        </div>
        <div class="col-lg-4 col-11 row text-left">
        <div class='col-lg-12 col-6 mb-2 mb-lg-0'>
          <%= link_to comment.user.name, user_path(comment.user), class: ''%>
          <br />
          Published : <%= time_ago_in_words comment.created_at %> ago
          </div>
          <div class='commentButtons col-6 col-lg-12 text-right d-flex align-items-center'>
          <% if current_user == comment.user %>
          <%= link_to "Edit", edit_comment_path(comment), class:"btn btn-dark btn-sm mr-2" %>
          <%= link_to "Delete", comment_path(comment), method: :delete, class:"btn btn-sm btn-danger" %> 
          <%end%>
          </div>
        </div>
      <div class="col-lg-7 d-flex align-items-center bg-white rounded">
        <p class="card-text commentText"><%= comment.content %></p>
      </div>
      </div>
    </div>
<% end %>
<%= render "posts/comment_form" %>