config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts
  resources :users, only: %i[show index]
  resources :comments, only: %i[create destroy update edit]
  resources :likes, only: %i[create destroy]
  resources :friendships, only: %i[create update destroy]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-teal">
  <a class="navbar-brand" href="/">
  <%= image_tag('snap.png', class:'img-fluid logoIndex')%>
  </a>
  <div class="user">
  <%= image_tag current_user.image_link+"?s=40",class:"rounded-circle" %>
    <%= current_user.name%>
</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse d-lg-flex justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'All users',users_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit account', edit_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Profile', user_path(current_user), class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Friends', users_path(filter: 'friends'), class:"nav-link"%>
      </li>
      <%if pending_request_count>0%>
        <li class="nav-item">
          <%= link_to  users_path(filter: 'pending'), class:"nav-link" do %>
            Notifications
            <span class="badge badge-pill d-inline badge-danger"><%= pending_request_count  %></span>
          <%end%>
        </li>
      <%end%>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link"%>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>FinalProject</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <%if user_signed_in?%>
  <header>
    <%= render 'layouts/navbar' %>
  </header>
  <% end %>
  <%if !notice.nil?  %>
  <div class='text-center w-100'>
    <p class="notice bg-success text-white py-3"><%= notice %></p>
  </div>
  <% end %>
  <%if !alert.nil? %>
  <div class='text-center w-100'>
    <p class="alert bg-danger text-white"><%= alert %></p>
  </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
</body>

</html>